export const LOAD_OFFERS = 'LOAD_OFFERS';
export const LOADING_OFFERS = 'LOADING_OFFERS';
export const LOAD_OFFERS_SUCCESS = 'LOAD_OFFERS_SUCCESS';
export const LOAD_OFFERS_FAILED = 'LOAD_OFFERS_FAILED';
export const LOAD_SORTED_OFFERS = 'LOAD_SORTED_OFFERS';